apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - grafana-helmrepository.yaml
  - grafana-token-sealedsecret.yaml
  - mcp-grafana-helmrelease.yaml
  - mcp-grafana-httproute.yaml
