apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - comfyui-deployment.yaml
  - comfyui-httproute.yaml
  - comfyui-pvc.yaml
  - comfyui-replicationsource.yaml
  - comfyui-replicationdestination.yaml
  - comfyui-service.yaml
  - restic-comfyui-sealedsecret.yaml