apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - kubernetes-mcp-server-ocirepository.yaml
  - mcp-kubernetes-helmrelease.yaml
  - mcp-kubernetes-httproute.yaml
