apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - kubernetes-mcp-httproute.yaml
  - kubernetes-mcp-server-helmrelease.yaml
  - kubernetes-mcp-server-ocirepository.yaml
