apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - mcp-photoprism-xiaowen-deployment.yaml
  - mcp-photoprism-xiaowen-httproute.yaml
  - mcp-photoprism-xiaowen-service.yaml
  - photoprism-xiaowen-sealedsecret.yaml
