apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - llm-httproute.yaml
  - open-webui-helmrelease.yaml
  - open-webui-helmrepository.yaml
  - open-webui-pvc.yaml
  - open-webui-replicationdestination.yaml
  - open-webui-replicationsource.yaml
  - restic-open-webui-sealedsecret.yaml